[2025-03-10 08:48:14,308] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: xkcd_daily.fetch_xkcd_data 2025-03-10T08:43:12.725191+00:00 [queued]>
[2025-03-10 08:48:14,316] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: xkcd_daily.fetch_xkcd_data 2025-03-10T08:43:12.725191+00:00 [queued]>
[2025-03-10 08:48:14,317] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-03-10 08:48:14,317] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2025-03-10 08:48:14,317] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-03-10 08:48:14,323] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): fetch_xkcd_data> on 2025-03-10T08:43:12.725191+00:00
[2025-03-10 08:48:14,325] {standard_task_runner.py:52} INFO - Started process 194 to run task
[2025-03-10 08:48:14,327] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'xkcd_daily', 'fetch_xkcd_data', '2025-03-10T08:43:12.725191+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/XKCD_daily/dag.py', '--cfg-path', '/tmp/tmpo1vjm1dy', '--error-file', '/tmp/tmpgxixzj1t']
[2025-03-10 08:48:14,329] {standard_task_runner.py:77} INFO - Job 6: Subtask fetch_xkcd_data
[2025-03-10 08:48:14,350] {logging_mixin.py:104} INFO - Running <TaskInstance: xkcd_daily.fetch_xkcd_data 2025-03-10T08:43:12.725191+00:00 [running]> on host 9064500c1350
[2025-03-10 08:48:14,375] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xkcd_daily
AIRFLOW_CTX_TASK_ID=fetch_xkcd_data
AIRFLOW_CTX_EXECUTION_DATE=2025-03-10T08:43:12.725191+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-10T08:43:12.725191+00:00
[2025-03-10 08:48:14,379] {base.py:78} INFO - Using connection to: id: xkcd_api. Host: https://xkcd.com, Port: None, Schema: None, Login: None, Password: None, extra: {'endpoint': '/info.0.json'}
[2025-03-10 08:48:14,482] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/XKCD_daily/dag.py", line 30, in fetch_xkcd_data
    data = response.json()
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2025-03-10 08:48:14,487] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=xkcd_daily, task_id=fetch_xkcd_data, execution_date=20250310T084312, start_date=20250310T084814, end_date=20250310T084814
[2025-03-10 08:48:14,539] {local_task_job.py:149} INFO - Task exited with return code 1
