[2025-03-10 09:05:59,787] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: xkcd_daily.xkcd_data_sensor 2025-03-10T09:05:57.726913+00:00 [queued]>
[2025-03-10 09:05:59,794] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: xkcd_daily.xkcd_data_sensor 2025-03-10T09:05:57.726913+00:00 [queued]>
[2025-03-10 09:05:59,794] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-03-10 09:05:59,799] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2025-03-10 09:05:59,803] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-03-10 09:05:59,816] {taskinstance.py:1107} INFO - Executing <Task(XKCDDataSensor): xkcd_data_sensor> on 2025-03-10T09:05:57.726913+00:00
[2025-03-10 09:05:59,820] {standard_task_runner.py:52} INFO - Started process 188 to run task
[2025-03-10 09:05:59,822] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'xkcd_daily', 'xkcd_data_sensor', '2025-03-10T09:05:57.726913+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/XKCD_daily/dag.py', '--cfg-path', '/tmp/tmpamrn0v4z', '--error-file', '/tmp/tmptxa1lvin']
[2025-03-10 09:05:59,826] {standard_task_runner.py:77} INFO - Job 4: Subtask xkcd_data_sensor
[2025-03-10 09:05:59,854] {logging_mixin.py:104} INFO - Running <TaskInstance: xkcd_daily.xkcd_data_sensor 2025-03-10T09:05:57.726913+00:00 [running]> on host dfff7782b6a2
[2025-03-10 09:05:59,880] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xkcd_daily
AIRFLOW_CTX_TASK_ID=xkcd_data_sensor
AIRFLOW_CTX_EXECUTION_DATE=2025-03-10T09:05:57.726913+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-10T09:05:57.726913+00:00
[2025-03-10 09:05:59,885] {base.py:78} INFO - Using connection to: id: xkcd_api. Host: https://xkcd.com/info.0.json, Port: None, Schema: None, Login: None, Password: None, extra: {}
[2025-03-10 09:05:59,945] {logging_mixin.py:104} INFO - Fetched XKCD Data: {'month': '3', 'num': 3060, 'link': '', 'year': '2025', 'news': '', 'safe_title': 'Omniroll', 'transcript': '', 'alt': 'It seems wrong that Fruit by the Foot is only sold by weight or by number of rolls.', 'img': 'https://imgs.xkcd.com/comics/omniroll.png', 'title': 'Omniroll', 'day': '7'}
[2025-03-10 09:05:59,954] {base.py:78} INFO - Using connection to: id: ***_postgresql. Host: ***, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2025-03-10 09:05:59,956] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/sensors/base.py", line 231, in execute
    while not self.poke(context):
  File "/usr/local/airflow/dags/XKCD_daily/dag.py", line 91, in poke
    if check_xkcd_data(xkcd_data):
  File "/usr/local/airflow/dags/XKCD_daily/dag.py", line 45, in check_xkcd_data
    cursor.execute("SELECT MAX(num) FROM xkcd_comics")
psycopg2.errors.UndefinedTable: relation "xkcd_comics" does not exist
LINE 1: SELECT MAX(num) FROM xkcd_comics
                             ^

[2025-03-10 09:05:59,971] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=xkcd_daily, task_id=xkcd_data_sensor, execution_date=20250310T090557, start_date=20250310T090559, end_date=20250310T090559
[2025-03-10 09:05:59,995] {local_task_job.py:149} INFO - Task exited with return code 1
