[0m09:56:11.096863 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1d1baef620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1d1cc31590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1d1b09c690>]}


============================== 09:56:11.103921 | 35ad0025-5c70-4025-9c04-1fd20cacb294 ==============================
[0m09:56:11.103921 [info ] [MainThread]: Running with dbt=1.9.3
[0m09:56:11.104500 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init transformations', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:56:11.115031 [info ] [MainThread]: Creating dbt configuration folder at /dbt
[0m09:56:11.115815 [error] [MainThread]: Encountered an error:
[Errno 13] Permission denied: '/dbt'
[0m09:56:11.118876 [error] [MainThread]: Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
  File "/usr/local/lib/python3.13/site-packages/dbt/task/init.py", line 300, in run
    self.create_profiles_dir(profiles_dir)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/dbt/task/init.py", line 69, in create_profiles_dir
    dbt_common.clients.system.make_directory(profiles_dir)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/functools.py", line 931, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/dbt_common/clients/system.py", line 209, in _
    raise e
  File "/usr/local/lib/python3.13/site-packages/dbt_common/clients/system.py", line 203, in _
    os.makedirs(path)
    ~~~~~~~~~~~^^^^^^
  File "<frozen os>", line 227, in makedirs
PermissionError: [Errno 13] Permission denied: '/dbt'

[0m09:56:11.120411 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 0.057642367, "process_in_blocks": "75472", "process_kernel_time": 0.049526, "process_mem_max_rss": "93348", "process_out_blocks": "0", "process_user_time": 0.841954}
[0m09:56:11.120831 [debug] [MainThread]: Command `dbt init` failed at 09:56:11.120740 after 0.06 seconds
[0m09:56:11.121327 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1d1ab4f5c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1d1a9edfd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1d1a9be030>]}
[0m09:56:11.121743 [debug] [MainThread]: Flushing usage events
[0m09:56:11.559935 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:56:37.813178 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff251d33620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff252e49590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff2510f8690>]}


============================== 09:56:37.817797 | 8b61f414-743f-4fae-be9c-7b8ef2e65f7f ==============================
[0m09:56:37.817797 [info ] [MainThread]: Running with dbt=1.9.3
[0m09:56:37.818237 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init ./transformations', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m09:56:37.822333 [info ] [MainThread]: Creating dbt configuration folder at /dbt
[0m09:56:37.822741 [error] [MainThread]: Encountered an error:
[Errno 13] Permission denied: '/dbt'
[0m09:56:37.824503 [error] [MainThread]: Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
  File "/usr/local/lib/python3.13/site-packages/dbt/task/init.py", line 300, in run
    self.create_profiles_dir(profiles_dir)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/dbt/task/init.py", line 69, in create_profiles_dir
    dbt_common.clients.system.make_directory(profiles_dir)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/functools.py", line 931, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/dbt_common/clients/system.py", line 209, in _
    raise e
  File "/usr/local/lib/python3.13/site-packages/dbt_common/clients/system.py", line 203, in _
    os.makedirs(path)
    ~~~~~~~~~~~^^^^^^
  File "<frozen os>", line 227, in makedirs
PermissionError: [Errno 13] Permission denied: '/dbt'

[0m09:56:37.825308 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 0.04552454, "process_in_blocks": "0", "process_kernel_time": 0.089369, "process_mem_max_rss": "93656", "process_out_blocks": "0", "process_user_time": 0.724886}
[0m09:56:37.825707 [debug] [MainThread]: Command `dbt init` failed at 09:56:37.825601 after 0.05 seconds
[0m09:56:37.826478 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff250d975c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff250c35fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff250c0e030>]}
[0m09:56:37.827219 [debug] [MainThread]: Flushing usage events
[0m09:56:38.281277 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:12:47.193360 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc344b53620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc345c9d590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc34411c690>]}


============================== 10:12:47.198865 | 25bf9e35-0b04-42bf-83a4-4c65cb098f77 ==============================
[0m10:12:47.198865 [info ] [MainThread]: Running with dbt=1.9.3
[0m10:12:47.199365 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init transformations', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m10:12:47.207886 [info ] [MainThread]: Creating dbt configuration folder at /dbt
[0m10:12:47.209337 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.13/site-packages/dbt/include/starter_project
[0m10:12:47.336103 [info ] [MainThread]: 
Your new dbt project "transformations" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m10:12:47.336532 [info ] [MainThread]: Setting up your profile.
[0m10:13:35.131542 [info ] [MainThread]: Profile transformations written to /dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m10:13:35.142738 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 47.98554, "process_in_blocks": "59440", "process_kernel_time": 0.134365, "process_mem_max_rss": "96848", "process_out_blocks": "1704", "process_user_time": 0.766851}
[0m10:13:35.143570 [debug] [MainThread]: Command `dbt init` succeeded at 10:13:35.143406 after 47.99 seconds
[0m10:13:35.144045 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc343b0dba0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc3440ad490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc343a32ad0>]}
[0m10:13:35.144480 [debug] [MainThread]: Flushing usage events
[0m10:13:35.590288 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:20:53.217012 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efc2b04ea50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efc2c11d1d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efc2a4c7d90>]}


============================== 10:20:53.219257 | 0468aeb1-0df4-444e-9d99-fbb60c023790 ==============================
[0m10:20:53.219257 [info ] [MainThread]: Running with dbt=1.9.3
[0m10:20:53.219850 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m10:20:53.225200 [info ] [MainThread]: dbt version: 1.9.3
[0m10:20:53.225986 [info ] [MainThread]: python version: 3.13.1
[0m10:20:53.226403 [info ] [MainThread]: python path: /usr/local/bin/python3.13
[0m10:20:53.226964 [info ] [MainThread]: os info: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[0m10:20:53.259938 [info ] [MainThread]: Using profiles dir at /dbt
[0m10:20:53.260402 [info ] [MainThread]: Using profiles.yml file at /dbt/profiles.yml
[0m10:20:53.260866 [info ] [MainThread]: Using dbt_project.yml file at /usr/app/dbt/dbt_project.yml
[0m10:20:53.261380 [info ] [MainThread]: adapter type: postgres
[0m10:20:53.261736 [info ] [MainThread]: adapter version: 1.9.0
[0m10:20:53.262282 [info ] [MainThread]: Configuration:
[0m10:20:53.262794 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m10:20:53.263189 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m10:20:53.263591 [info ] [MainThread]: Required dependencies:
[0m10:20:53.264077 [debug] [MainThread]: Executing "git --help"
[0m10:20:53.265115 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m10:20:53.265405 [debug] [MainThread]: STDERR: "b''"
[0m10:20:53.265651 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m10:20:53.265894 [info ] [MainThread]: Connection:
[0m10:20:53.266251 [info ] [MainThread]:   host: dwh
[0m10:20:53.266750 [info ] [MainThread]:   port: 5432
[0m10:20:53.267007 [info ] [MainThread]:   user: dwh
[0m10:20:53.267337 [info ] [MainThread]:   database: dwh
[0m10:20:53.267690 [info ] [MainThread]:   schema: dwh
[0m10:20:53.267986 [info ] [MainThread]:   connect_timeout: 10
[0m10:20:53.268271 [info ] [MainThread]:   role: None
[0m10:20:53.268569 [info ] [MainThread]:   search_path: None
[0m10:20:53.268844 [info ] [MainThread]:   keepalives_idle: 0
[0m10:20:53.269158 [info ] [MainThread]:   sslmode: None
[0m10:20:53.269446 [info ] [MainThread]:   sslcert: None
[0m10:20:53.269794 [info ] [MainThread]:   sslkey: None
[0m10:20:53.270082 [info ] [MainThread]:   sslrootcert: None
[0m10:20:53.270386 [info ] [MainThread]:   application_name: dbt
[0m10:20:53.270684 [info ] [MainThread]:   retries: 1
[0m10:20:53.271097 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m10:20:53.295863 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m10:20:53.309778 [debug] [MainThread]: Using postgres connection "debug"
[0m10:20:53.310247 [debug] [MainThread]: On debug: select 1 as id
[0m10:20:53.310525 [debug] [MainThread]: Opening a new connection, currently in state init
[0m10:20:53.313337 [debug] [MainThread]: SQL status: SELECT 1 in 0.003 seconds
[0m10:20:53.314109 [debug] [MainThread]: On debug: Close
[0m10:20:53.314396 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m10:20:53.314693 [info ] [MainThread]: [31m1 check failed:[0m
[0m10:20:53.315175 [info ] [MainThread]: Project loading failed for the following reason:
 project path </usr/app/dbt/dbt_project.yml> not found

[0m10:20:53.316034 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.13692869, "process_in_blocks": "0", "process_kernel_time": 0.039898, "process_mem_max_rss": "103840", "process_out_blocks": "0", "process_user_time": 0.797968}
[0m10:20:53.316358 [debug] [MainThread]: Command `dbt debug` failed at 10:20:53.316297 after 0.14 seconds
[0m10:20:53.316611 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m10:20:53.316839 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efc28de4180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efc29905b50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efc2a057240>]}
[0m10:20:53.317102 [debug] [MainThread]: Flushing usage events
[0m10:20:53.760916 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:24:45.470867 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd9f3a03620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd9f4b3d590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd9f2f9c690>]}


============================== 16:24:45.476058 | 9f6249fd-94f4-4193-b3a1-762e2af02346 ==============================
[0m16:24:45.476058 [info ] [MainThread]: Running with dbt=1.9.3
[0m16:24:45.477348 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt test', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:24:45.478690 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:24:45.480179 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.04932366, "process_in_blocks": "75144", "process_kernel_time": 0.090274, "process_mem_max_rss": "92816", "process_out_blocks": "1696", "process_user_time": 0.802436}
[0m16:24:45.480675 [debug] [MainThread]: Command `dbt test` failed at 16:24:45.480597 after 0.05 seconds
[0m16:24:45.481319 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd9f2a31e00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd9f2b8a0f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd9f2ab3460>]}
[0m16:24:45.481943 [debug] [MainThread]: Flushing usage events
[0m16:24:45.951164 [debug] [MainThread]: An error was encountered while trying to flush usage events
