[2025-03-10 09:20:45,353] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: xkcd_batch_loader.store_xkcd_data 2025-03-10T09:20:44.171151+00:00 [queued]>
[2025-03-10 09:20:45,360] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: xkcd_batch_loader.store_xkcd_data 2025-03-10T09:20:44.171151+00:00 [queued]>
[2025-03-10 09:20:45,360] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2025-03-10 09:20:45,361] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2025-03-10 09:20:45,361] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2025-03-10 09:20:45,369] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): store_xkcd_data> on 2025-03-10T09:20:44.171151+00:00
[2025-03-10 09:20:45,370] {standard_task_runner.py:52} INFO - Started process 432 to run task
[2025-03-10 09:20:45,372] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'xkcd_batch_loader', 'store_xkcd_data', '2025-03-10T09:20:44.171151+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/XKCD_batch/dag.py', '--cfg-path', '/tmp/tmpoh8mi4jn', '--error-file', '/tmp/tmpsi4eltbh']
[2025-03-10 09:20:45,374] {standard_task_runner.py:77} INFO - Job 11: Subtask store_xkcd_data
[2025-03-10 09:20:45,396] {logging_mixin.py:104} INFO - Running <TaskInstance: xkcd_batch_loader.store_xkcd_data 2025-03-10T09:20:44.171151+00:00 [running]> on host dfff7782b6a2
[2025-03-10 09:20:45,422] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xkcd_batch_loader
AIRFLOW_CTX_TASK_ID=store_xkcd_data
AIRFLOW_CTX_EXECUTION_DATE=2025-03-10T09:20:44.171151+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-10T09:20:44.171151+00:00
[2025-03-10 09:20:45,431] {base.py:78} INFO - Using connection to: id: ***_postgresql. Host: ***, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2025-03-10 09:20:45,437] {base.py:78} INFO - Using connection to: id: ***_postgresql. Host: ***, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2025-03-10 09:20:45,439] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/XKCD_batch/dag.py", line 58, in store_xkcd_data
    while backlog_startpoint <= latest_num:
TypeError: '<=' not supported between instances of 'str' and 'int'
[2025-03-10 09:20:45,441] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=xkcd_batch_loader, task_id=store_xkcd_data, execution_date=20250310T092044, start_date=20250310T092045, end_date=20250310T092045
[2025-03-10 09:20:45,464] {local_task_job.py:149} INFO - Task exited with return code 1
